import crypto from 'node:crypto';

// Plain SHA-256 of a viewer-supplied trust secret. The secret itself is
// generated by the host as 32+ random bytes so HMAC keying is unnecessary.
// A plain hash means host (which may not share SESSION_SECRET) and server
// always compute the same value.
export function hashTrustSecret(secret) {
  return crypto.createHash('sha256').update(String(secret)).digest('hex');
}
